#rule
#等级0，即学生或者老师或者高级管理员可查看个人信息，对部分信息进行增删改
role0:
  id: 0
  #Resource
  host: "*"
  path: "/*/*"
  method: "{POST,GET}"
  #Permission
  authorized_roles:
    - "*"
  forbidden_roles:
    - visitor
  allow_anyone: false

#等级1，即老师或者高级管理员可以对选课学生进行增删改查的操作
role1:
  id: 1
  #Resource
  host: teacher.com
  path: "/*/*"
  method: "*"
  #Permission
  authorized_roles:
    - teacher
    - administrator
  forbiddenRoles:
    - visitor
    - student
  AllowAnyone: false

#等级2，即高级管理员可以对老师以及学生的所有信息进行增删改查
role2:
  id: 2
  #Resource
  host: administrator.com
  path: "/*/*"
  method: "*"
  #Permission
  authorized_roles:
    - administrator
  forbiddenRoles:
    - visitor
    - student
    - teacher
  AllowAnyone: false